package eu.trentorise.game.model

import eu.trentorise.game.notification.MessageNotification;
import eu.trentorise.game.model.PointConcept;
import eu.trentorise.game.model.PointConcept.PeriodInstance;


function Double findPeriodicMax(PointConcept pc, String pName) {
	Double ret = 0.0;
	PeriodInstance pi = pc.getPeriodCurrentInstance(pName);
	int i = pi.getIndex();
	while (i >= 0) {
		pi = pc.getPeriodInstance(pName, i--);
		Double s = pi.getScore();
		if(s > ret)
			ret = pi.getScore();
	}
	
	return ret;
}

rule "R-check-record-distance"
when
	Action(id == "WeeklyTaskTest") // simulates triggering of weekly task
	InputData( $c : data["counter"])
	$pc : PointConcept(name == (String)$c)
	Player($teamId : id, team == true) // only works with teams
	Game( $gameId: id)
then
	log("apply \'R-check-record-distance\'");
	Double current = $pc.getPeriodCurrentScore("weekly");
	Double max = findPeriodicMax($pc,"weekly");
	if (current.equals(max)) {
		MessageNotification mn = new MessageNotification($gameId,$teamId, 'Nuovo record settimanalte: ');
		mn.addData("score", $c);
		mn.addData("record", current);
		insert(mn);
	}
end
