package eu.trentorise.game.model

rule "class trip update"
when
    Action(id == "ClassWalkTrip")
    Player($playerId : id, team == true) // this actions is valid only for classes/teams
    InputData( $distance : data["class-distance"] != null, 
    	$num : data["participants"]!= null, $meteo : data["meteo"] != null, $date : data["school-date"] != null )
    $tot_dist : PointConcept(name == "total_distance")
    $tot_trips : PointConcept(name == "total_trips")
    $mode_dist : PointConcept(name == "zeroImpact_wAdult_distance")
    $mode_trips : PointConcept(name == "zeroImpact_wAdult_trips")
then
	log("apply class trip with " + $num + " participants");
		
	//for now no Meteo bonus ???
	Double tripDistance = (Double)$num * (Double)$distance;
	$mode_dist.setScore($mode_dist.getScore() + tripDistance);
	$mode_trips.setScore($mode_trips.getScore() + (Double)$num);
	$tot_dist.setScore($tot_dist.getScore() + tripDistance);
	$tot_trips.setScore($tot_trips.getScore() + (Double)$num);

    update($mode_dist);
    update($mode_trips);
    update($tot_dist);
    update($tot_trips);
    insert(new UpdateTeams());	
end

rule "class trip propagation"
when
    Member( $distance : inputData["class-distance"] != null, 
    	$num : inputData["participants"]!= null, $meteo : inputData["meteo"] != null, $date : inputData["school-date"] != null )
    Player($playerId : id, team == true)
    $tot_dist : PointConcept(name == "total_distance")
    $tot_trips : PointConcept(name == "total_trips")
    $mode_dist : PointConcept(name == "zeroImpact_wAdult_distance")
    $mode_trips : PointConcept(name == "zeroImpact_wAdult_trips")
then
	log("apply class trip with " + $num + " participants update propagation");
		
	//for now no Meteo bonus ???
	Double tripDistance = (Double)$num * (Double)$distance;
	$mode_dist.setScore($mode_dist.getScore() + tripDistance);
	$mode_trips.setScore($mode_trips.getScore() + (Double)$num);
	$tot_dist.setScore($tot_dist.getScore() + tripDistance);
	$tot_trips.setScore($tot_trips.getScore() + (Double)$num);

    update($mode_dist);
    update($mode_trips);
    update($tot_dist);
    update($tot_trips);
    insert(new UpdateTeams());
end