package eu.trentorise.game.model
import eu.trentorise.game.core.Utility;

global Utility utils;
global String badge_collection_name;
global String const_school_name;

// only applies to SCHOOL!

rule 'ch-ViaggiGiornalieri-check'
salience -1000
when
   $challenge : ChallengeConcept( modelName == "ViaggiGiornalieri_PassaggioVersoTappa", 
		$target: fields["target"], $vp : fields["VirtualPrize"],
		$bonusScore : fields["bonusScore"], 
		isCompleted() != true ) 
	Player($teamId : id, team == true, $teamId == const_school_name) // only applies to SCHOOL
	BadgeCollectionConcept( name == badge_collection_name, 
    	badgeEarned contains (String)$leg || $leg == null ) // either they have reached a leg or no leg info in challenge 
	$zSolo : PointConcept(name == "zeroImpact_solo_trips" )
	$zAdult : PointConcept(name == "zeroImpact_wAdult_trips" )
	$pedibus : PointConcept(name == "pedibus_trips" )
	$tot_dist : PointConcept(name == "total_distance")  
	Game( $gameId: id) 
then
	utils.log("apply \'ch-ViaggiGiornalieri_PassaggioVersoTappa-check\' with Prize: " + $vp);
	Double todayTrips = $zSolo.getPeriodCurrentScore("daily") 
		+ $zAdult.getPeriodCurrentScore("daily")
		+ $pedibus.getPeriodCurrentScore("daily");
	if (todayTrips.compareTo((Double)$target) >= 0) {// challenge was won
		utils.log("Challenge ViaggiGiornalieri_PassaggioVersoTappa HAS BEEN WON by: " + $teamId);
		MessageNotification mn = new MessageNotification($gameId,$teamId,"ChallengeWon");
		mn.addData("_VirtualPrize_", $vp);
		insert(mn);
		$challenge.completed();
    	update($challenge);  	  	
	}
end

rule 'ch-ViaggiGiornalieri-award'
salience -5000
when
	$challenge : ChallengeConcept( modelName == "ViaggiGiornalieri_PassaggioVersoTappa", isCompleted() != true,
		$leg : fields["legName"], $vp : fields["VirtualPrize"], $pw : fields["prizeWon"]== true,
		$bonusPointType : fields["bonusPointType"], $bonusScore : fields["bonusScore"] )
	Player($teamId : id, team == true)
    $id : InputData()
    BadgeCollectionConcept( name == badge_collection_name, 
    	badgeEarned contains (String)$leg || $leg == null )
	$pc : PointConcept(name == (String) $bonusPointType)
	$tot_dist : PointConcept(name == "total_distance")
then
	utils.log("apply \'ch-ViaggiGiornalieri_PassaggioVersoTappa-award \' ");
    $pc.setScore($pc.getScore() +  (Double)$bonusScore);
	update($pc);
	if (! ((String)$bonusPointType).equals("total_distance")) {
		$tot_dist.setScore($tot_dist.getScore() +  (Double)$bonusScore);
		update($tot_dist);
	}
	$challenge.completed();
    update($challenge);
	
end

